// Fuente única del contenido del cuestionario TechSpec.
// La consumen index.html (cuestionario) y admin.html (panel de consolidación).
// Editar aquí una sola vez; ambos se actualizan. Cada fila: [requisito, default del stack RS].
window.TECHSPEC_CONTENT = (function(){
  const META = {
    icon:'◈', title:'Contexto general', desc:'Datos del proyecto y del entorno del cliente.',
    fields:['Empresa / unidad','Responsable técnico (cliente)','Responsable (RS)','Fecha de la sesión',
      'Nombre del proyecto / app','Nº de entornos (dev/staging/prod)','Nube corporativa (si la hay)','Idiomas de la app']
  };
  const SECTIONS = [
    { icon:'▤', title:'Frontend', desc:'Capa de interfaz de usuario.', rows:[
      ['Lenguaje','TypeScript'],
      ['Framework / librería UI','React 18'],
      ['Build tool / bundler','Vite'],
      ['Librería de componentes','MUI (Material UI) 5'],
      ['Estilado','MUI theme + Emotion (CSS-in-JS)'],
      ['Gestión de estado','React hooks + Context'],
      ['Routing','React Router'],
      ['Renderizado','SPA (cliente). ¿Necesitan SSR/estático?'],
      ['Navegadores soportados','Evergreen (últimas 2 versiones)'],
      ['Accesibilidad','WCAG 2.1 AA'],
      ['¿Prefieren otra cosa? (HTML plano, Angular, Vue, Blazor…)','—'],
    ]},
    { icon:'⚙', title:'Backend', desc:'Capa de servicio y lógica de negocio.', rows:[
      ['Lenguaje','Python 3.12+'],
      ['Framework','FastAPI'],
      ['Servidor de aplicación','Uvicorn (ASGI), puerto 8000'],
      ['Gestor de paquetes / entorno','uv'],
      ['Estilo de API','REST (OpenAPI / Swagger)'],
      ['Arquitectura','Clean Architecture / DDD (4 capas)'],
      ['Validación / serialización','Pydantic v2'],
      ['Tareas asíncronas / colas','No por defecto (¿Celery / RQ / bus?)'],
      ['¿Prefieren otra cosa? (.NET, Java/Spring, Node, Go…)','—'],
    ]},
    { icon:'⛃', title:'Base de datos y datos', desc:'Persistencia y ciclo de vida del dato.', rows:[
      ['Motor de base de datos','PostgreSQL'],
      ['ORM','SQLAlchemy 2.x'],
      ['Migraciones','Alembic'],
      ['Semántica de borrado','Soft-delete (deleted_at)'],
      ['Paginación','Server-side (page size 20)'],
      ['Backups y retención','A definir (frecuencia, retención, prueba de restore)'],
      ['Datos personales / PII','A definir (clasificación, minimización)'],
      ['¿Prefieren otro motor? (SQL Server, Oracle, MySQL, Mongo…)','—'],
    ]},
    { icon:'☁', title:'Infraestructura y hosting', desc:'Dónde y cómo se ejecuta.', rows:[
      ['Entorno de desarrollo','Localhost (frontend 5173 / backend 8000)'],
      ['Nube de despliegue','Azure — AKS (Kubernetes)'],
      ['Registro de contenedores','Azure Container Registry (ACR)'],
      ['Orquestación','Kubernetes (AKS) con overlays dev/staging/prod'],
      ['Motor de contenedores (build local)','Podman (Docker fallback)'],
      ['Infraestructura como código (IaC)','Manifiestos k8s. ¿Terraform / Bicep?'],
      ['Secretos en runtime','Azure Key Vault + Secrets Store CSI Driver'],
      ['Regiones / residencia de datos','A definir (¿UE?)'],
      ['¿Prefieren otro proveedor? (AWS, GCP, on-premise, híbrido)','—'],
    ]},
    { icon:'⟲', title:'CI/CD y DevOps', desc:'Integración, entrega y despliegue.', rows:[
      ['Control de versiones','Git + GitHub'],
      ['Modelo de ramas','GitHub Flow (feature→dev, PR→staging, main→prod)'],
      ['Pipelines CI/CD','GitHub Actions'],
      ['Gate de calidad','make gate (tests+lint+types+audit) + hook pre-push'],
      ['Entornos','dev / staging / prod'],
      ['Estrategia de despliegue','Rolling. ¿Blue-green / canary?'],
      ['¿Prefieren otra plataforma? (GitLab CI, Azure DevOps, Jenkins…)','—'],
    ]},
    { icon:'🔑', title:'Autenticación y autorización', desc:'Identidad y control de acceso.', rows:[
      ['Autenticación de la app','Ninguna por defecto (según brief funcional)'],
      ['Proveedor de identidad','A definir (¿Entra ID / Azure AD, LDAP/AD on-prem?)'],
      ['Protocolo','A definir (OIDC / SAML 2.0)'],
      ['MFA / doble factor','A definir'],
      ['Modelo de permisos','RBAC (roles a definir)'],
      ['Gestión de sesiones / tokens','A definir (JWT, cookies, expiración)'],
      ['SSO corporativo obligatorio','A definir'],
    ]},
    { icon:'🛡', title:'Ciberseguridad', desc:'Requisitos de seguridad y cumplimiento técnico.', rows:[
      ['Normativas / marcos','A definir (ISO 27001, ENS, NIST CSF…)'],
      ['Protección de datos','RGPD / GDPR'],
      ['Clasificación de la información','A definir (público/interno/confidencial)'],
      ['Cifrado en tránsito','TLS 1.2+ / HTTPS obligatorio'],
      ['Cifrado en reposo','A definir (BBDD, almacenamiento, backups)'],
      ['Gestión de secretos','Key Vault; nada de secretos en repo (.env solo local)'],
      ['SAST — análisis estático','A definir (Bandit / Semgrep / SonarQube…)'],
      ['DAST / pentesting','A definir (cadencia, proveedor)'],
      ['Escaneo de dependencias (CVE)','pip-audit + npm audit en el gate. ¿Snyk / Dependabot?'],
      ['Escaneo de imágenes de contenedor','A definir (Trivy / MS Defender)'],
      ['Política de dependencias / OSS','A definir (licencias permitidas, aprobación)'],
      ['Logging y auditoría','A definir (centralizado, retención, trazabilidad)'],
      ['Gestión de vulnerabilidades / parcheo','A definir (SLA por severidad)'],
      ['Respuesta a incidentes','A definir (proceso y contacto)'],
      ['Acceso a repos / código','A definir (SSO, 2FA, ramas protegidas, revisión)'],
      ['Red y perímetro','A definir (VPN, firewall, segmentación, ¿aislado?)'],
      ['Copias de seguridad y DR','A definir (RPO / RTO)'],
    ]},
    { icon:'✦', title:'Inteligencia artificial / LLM', desc:'Uso de IA en la app y en el proceso de desarrollo.', rows:[
      ['Proveedor LLM (en la app, si aplica)','Anthropic Claude (por defecto)'],
      ['¿Uso de IA permitido?','A definir (política corporativa)'],
      ['Gobernanza de datos con IA','No enviar PII / datos de cliente sin anonimizar'],
      ['EU AI Act — clasificación de riesgo','A definir'],
      ['Auditoría de seguridad IA','cyber-security-ai (OWASP LLM Top 10 + EU AI Act)'],
      ['Modelos privados / on-premise','A definir (¿Azure OpenAI, modelos locales?)'],
      ['Residencia de datos de IA','A definir (¿UE?)'],
    ]},
    { icon:'✓', title:'Testing y QA', desc:'Estrategia de pruebas y calidad.', rows:[
      ['Unit backend','pytest'],
      ['Integración','testcontainers (PostgreSQL real)'],
      ['End-to-end','Playwright (headed)'],
      ['Rendimiento / carga','Locust (cuando aplique)'],
      ['Unit frontend','Vitest + React Testing Library'],
      ['Cobertura mínima','≥ 80%'],
      ['Lint / formato / tipos','ruff, mypy, eslint'],
      ['¿Herramientas de QA corporativas?','—'],
    ]},
    { icon:'◔', title:'Observabilidad', desc:'Logs, métricas y trazas en producción.', rows:[
      ['Logging','A definir (estructurado; destino: Azure Monitor / ELK / Datadog)'],
      ['Métricas y monitorización','A definir (Prometheus / Grafana / Azure Monitor)'],
      ['Tracing distribuido','A definir (OpenTelemetry)'],
      ['Gestión de errores / APM','A definir (Sentry / App Insights)'],
      ['Alertas','A definir (umbrales, canales)'],
    ]},
    { icon:'§', title:'Compliance y legal', desc:'Cumplimiento normativo y contractual.', rows:[
      ['Regulaciones aplicables','A definir (RGPD + normativas sectoriales del cliente)'],
      ['Residencia / soberanía del dato','A definir (¿UE / España?)'],
      ['Certificaciones exigidas al proveedor','A definir'],
      ['Acuerdos','A definir (NDA, DPA, SLA)'],
      ['Propiedad del código / IP','A definir'],
    ]},
    { icon:'⇄', title:'Integraciones', desc:'Conexión con los sistemas existentes de la organización.', rows:[
      ['Sistemas a integrar','A definir (ERP, CRM, IoT, data warehouse…)'],
      ['Protocolos','A definir (REST, SOAP, gRPC, MQTT, OPC-UA…)'],
      ['Autenticación entre sistemas','A definir (API keys, OAuth2, mTLS)'],
      ['Formatos de intercambio','A definir (JSON, XML, CSV)'],
    ]},
    { icon:'⚖', title:'Licenciamiento y procurement', desc:'Restricciones de software y proveedores.', rows:[
      ['Política de open source','A definir (¿MIT/Apache OK? ¿copyleft/GPL restringido?)'],
      ['Herramientas corporativas obligatorias','A definir'],
      ['Restricciones de proveedor cloud','A definir (¿solo Azure? ¿multi-cloud?)'],
      ['Aprobación de nuevas dependencias','A definir (proceso)'],
    ]},
  ];
  return { META, SECTIONS };
})();
